# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 遇见的 Blog
description: > # this means to ignore newlines until "baseurl:"
  个人blog，记录技术点滴.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bruce-xu.github.io" # the base hostname & protocol for your site
github_username:  bruce-xu
pages: ""

# Build settings
markdown: kramdown
